### ISSUE TITLE
Etapa 6 - Teste

### ISSUE THREAD

**Issue by SamuelAlves977** [SamuelAlves977/Sistema-de-Controle-de-Vacinacao#9]
Etapa 6 – Teste
Elaborar um plano de teste para o Sistema
Potenciais ferramentas: Planilha de planejamento e casos de teste

[Plano de Teste.xlsx](https://github.com/SamuelAlves977/Sistema-de-Controle-de-Vacinacao/files/6645418/Plano.de.Teste.xlsx)

**Comment by Eduwilll** [comment]
a
